version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_DATABASE: "wordpress_db"
      MYSQL_USER: "wordpress_user"
      MYSQL_PASSWORD: "wp_user_pass"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    container_name: wordpress_app
    restart: always
    environment:
      WORDPRESS_DB_HOST: "mysql" # Aponta para o serviço mysql
      WORDPRESS_DB_USER: "wordpress_user"
      WORDPRESS_DB_PASSWORD: "wp_user_pass"
      WORDPRESS_DB_NAME: "wordpress_db"
      # As linhas abaixo ajudam o WordPress a entender que ele está rodando em um subdiretório
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/prova');
        define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . '/prova');
    volumes:
      - wp_data:/var/www/html
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ui
    restart: always
    environment:
      PMA_HOST: "mysql"
      MYSQL_ROOT_PASSWORD: "root123"
    ports:
      - "8081:80" # Acessível em http://localhost:8081
    networks:
      - app-network
volumes:
  db_data:
  wp_data:

networks:
  app-network:
    driver: bridge